sudo: required

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo service docker restart

script:
  - cd prometheus && docker build -t stefanprodan/swarmprom-prometheus:$TRAVIS_BUILD_NUMBER .
  - cd .. && cd node-exporter && docker build -t smartuser/swarmprom_node-exporter:$TRAVIS_BUILD_NUMBER .
  - cd .. && cd alertmanager && docker build -t smartuser/swarmprom_alertmanager:$TRAVIS_BUILD_NUMBER .
  - cd .. && cd grafana && docker build -t smartuser/swarmprom_grafana:$TRAVIS_BUILD_NUMBER .

after_success:
  - if [ -z "$DOCKER_USER" ]; then
      echo "PR build, skipping Docker Hub push";
    else
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
    docker tag stefanprodan/swarmprom-prometheus:$TRAVIS_BUILD_NUMBER stefanprodan/swarmprom-prometheus:v2.5.0;
    docker push stefanprodan/swarmprom-prometheus:v2.5.0;
    docker tag smartuser/swarmprom_node-exporter:$TRAVIS_BUILD_NUMBER smartuser/swarmprom_node-exporter:v1.3.1;
    docker push smartuser/swarmprom_node-exporter:v1.3.1;
    docker tag smartuser/swarmprom_node-exporter:$TRAVIS_BUILD_NUMBER smartuser/swarmprom_node-exporter;
    docker push smartuser/swarmprom_node-exporter;
    docker tag smartuser/swarmprom_alertmanager:$TRAVIS_BUILD_NUMBER smartuser/swarmprom_alertmanager:v0.24.0;
    docker push smartuser/swarmprom_alertmanager:v0.24.0;
    docker tag smartuser/swarmprom_alertmanager:$TRAVIS_BUILD_NUMBER smartuser/swarmprom_alertmanager;
    docker push smartuser/swarmprom_alertmanager;
    docker tag smartuser/swarmprom_grafana:$TRAVIS_BUILD_NUMBER smartuser/swarmprom_grafana:8.5.5;
    docker push smartuser/swarmprom_grafana:8.5.5;
    docker tag smartuser/swarmprom_grafana:$TRAVIS_BUILD_NUMBER smartuser/swarmprom_grafana;
    docker push smartuser/swarmprom_grafana;
    fi
